export type DataSource = {
  name: string;
  publisher: string;
  description: string;
  region: "US" | "Europe" | "US + Europe" | "Global — filter US/EU";
  domain:
    | "Health"
    | "Wearables"
    | "Population"
    | "Economy"
    | "Environment"
    | "Mobility"
    | "Government"
    | "Knowledge"
    | "Culture"
    | "Technology";
  license: string;
  licenseClass: "Public domain" | "Attribution" | "Share-alike" | "Open-filtered";
  access: string;
  mess: 1 | 2 | 3 | 4;
  lesson: string;
  url: string;
  featured?: boolean;
};

export const dataSources: DataSource[] = [
  {
    name: "Synthea synthetic health records",
    publisher: "MITRE",
    description: "Complete synthetic patient histories in FHIR, C-CDA, and relational CSV formats—without real-patient privacy restrictions.",
    region: "US",
    domain: "Health",
    license: "Apache 2.0 generator · unrestricted synthetic output",
    licenseClass: "Attribution",
    access: "Files + generator",
    mess: 3,
    lesson: "EHR schemas, longitudinal events, claims, synthetic-data validity",
    url: "https://synthetichealth.github.io/synthea/",
    featured: true,
  },
  {
    name: "CMS Provider Data Catalog",
    publisher: "Centers for Medicare & Medicaid Services",
    description: "Hospitals, nursing homes, hospice, dialysis, home health, staffing, quality measures, and geographic provider data.",
    region: "US",
    domain: "Health",
    license: "U.S. Public Domain",
    licenseClass: "Public domain",
    access: "CSV + API",
    mess: 3,
    lesson: "Provider comparison, quality measurement, suppressed values, changing definitions",
    url: "https://data.cms.gov/provider-data/",
    featured: true,
  },
  {
    name: "CDC Open Data",
    publisher: "Centers for Disease Control and Prevention",
    description: "Public-health surveillance spanning chronic disease, injury, vaccination, occupational health, and environmental exposures.",
    region: "US",
    domain: "Health",
    license: "U.S. Public Domain · verify item exceptions",
    licenseClass: "Public domain",
    access: "CSV + Socrata API",
    mess: 3,
    lesson: "Surveillance bias, revision cadence, rates versus counts",
    url: "https://data.cdc.gov/",
  },
  {
    name: "Eurostat health database",
    publisher: "European Commission / Eurostat",
    description: "Comparable European measures for health status, determinants, care, expenditure, causes of death, and workplace injury.",
    region: "Europe",
    domain: "Health",
    license: "EU reuse policy · attribution · check exceptions",
    licenseClass: "Attribution",
    access: "Bulk + SDMX API",
    mess: 3,
    lesson: "Cross-country comparability, harmonized indicators, missing-country patterns",
    url: "https://ec.europa.eu/eurostat/web/health/database",
    featured: true,
  },
  {
    name: "Human Activity Recognition using smartphones",
    publisher: "UCI Machine Learning Repository",
    description: "Accelerometer and gyroscope recordings from 30 people performing six everyday activities with a waist-mounted phone.",
    region: "Europe",
    domain: "Wearables",
    license: "CC BY 4.0",
    licenseClass: "Attribution",
    access: "ZIP + Python package",
    mess: 2,
    lesson: "Windowing, subject leakage, activity classification, sensor preprocessing",
    url: "https://archive.ics.uci.edu/dataset/240/human+activity+recognition+using+smartphones",
    featured: true,
  },
  {
    name: "PAMAP2 Physical Activity Monitoring",
    publisher: "UCI Machine Learning Repository",
    description: "Heart-rate and inertial measurements for 18 activities performed by nine people wearing wrist, chest, and ankle sensors.",
    region: "Europe",
    domain: "Wearables",
    license: "CC BY 4.0",
    licenseClass: "Attribution",
    access: "ZIP",
    mess: 4,
    lesson: "Sensor synchronization, transient labels, missing values, intensity estimation",
    url: "https://archive.ics.uci.edu/dataset/231/pamap2+physical+activity+monitoring",
    featured: true,
  },
  {
    name: "WISDM phone + watch activity",
    publisher: "UCI / Fordham University",
    description: "Raw phone and smartwatch accelerometer and gyroscope streams from 51 subjects performing 18 activities.",
    region: "US",
    domain: "Wearables",
    license: "CC BY 4.0",
    licenseClass: "Attribution",
    access: "ZIP",
    mess: 4,
    lesson: "Device heterogeneity, biometric leakage, sampling-rate drift",
    url: "https://archive.ics.uci.edu/dataset/507/wisdm+smartphone+and+smartwatch+activity+and+biometrics+dataset",
  },
  {
    name: "HAR70+",
    publisher: "UCI / Norwegian University of Science and Technology",
    description: "Professionally annotated accelerometer recordings from adults aged 70–95 in a semi-structured free-living protocol.",
    region: "Europe",
    domain: "Wearables",
    license: "CC BY 4.0",
    licenseClass: "Attribution",
    access: "CSV",
    mess: 2,
    lesson: "Small samples, older-adult representation, validation design",
    url: "https://archive.ics.uci.edu/dataset/780/har70",
  },
  {
    name: "selfBACK activity recognition",
    publisher: "UCI / selfBACK consortium",
    description: "Wrist and thigh accelerometer streams for nine ambulatory and sedentary activity classes across 33 participants.",
    region: "Europe",
    domain: "Wearables",
    license: "CC BY 4.0",
    licenseClass: "Attribution",
    access: "CSV",
    mess: 3,
    lesson: "Multi-sensor alignment, person-level validation, class boundaries",
    url: "https://archive.ics.uci.edu/dataset/521/selfback",
  },
  {
    name: "OPPORTUNITY activity recognition",
    publisher: "UCI / OPPORTUNITY consortium",
    description: "Body-worn, object, and ambient sensors capturing naturalistic daily activities in a sensor-rich environment.",
    region: "Europe",
    domain: "Wearables",
    license: "CC BY 4.0",
    licenseClass: "Attribution",
    access: "ZIP",
    mess: 4,
    lesson: "Sensor fusion, segmentation, sparse labels, multimodal failure",
    url: "https://archive.ics.uci.edu/dataset/226/opportunity+activity+recognition",
  },
  {
    name: "American Community Survey + PUMS",
    publisher: "U.S. Census Bureau",
    description: "Household, demographic, housing, education, employment, and income estimates plus person- and household-level public microdata.",
    region: "US",
    domain: "Population",
    license: "U.S. Public Domain",
    licenseClass: "Public domain",
    access: "API + CSV",
    mess: 3,
    lesson: "Survey weights, margins of error, geographic grain, disclosure protection",
    url: "https://www.census.gov/programs-surveys/acs/microdata.html",
    featured: true,
  },
  {
    name: "TIGER/Line geographies",
    publisher: "U.S. Census Bureau",
    description: "Roads, boundaries, water, address ranges, and census geographies designed to join with population data.",
    region: "US",
    domain: "Mobility",
    license: "U.S. Public Domain",
    licenseClass: "Public domain",
    access: "Shapefile + geodatabase",
    mess: 3,
    lesson: "Spatial joins, boundary vintages, geographic identifiers",
    url: "https://www.census.gov/geographies/mapping-files/time-series/geo/tiger-line-file.html",
  },
  {
    name: "Bureau of Labor Statistics public data",
    publisher: "U.S. Bureau of Labor Statistics",
    description: "Employment, wages, prices, productivity, occupations, injuries, and time-use series from many independent programs.",
    region: "US",
    domain: "Economy",
    license: "U.S. Public Domain",
    licenseClass: "Public domain",
    access: "API + files",
    mess: 3,
    lesson: "Seasonal adjustment, revisions, series identifiers, survey redesigns",
    url: "https://www.bls.gov/data/",
  },
  {
    name: "BEA economic accounts",
    publisher: "U.S. Bureau of Economic Analysis",
    description: "National, state, county, industry, trade, and international economic accounts with long historical series.",
    region: "US",
    domain: "Economy",
    license: "U.S. Public Domain",
    licenseClass: "Public domain",
    access: "API + tables",
    mess: 3,
    lesson: "Real versus nominal measures, chained dollars, revision vintages",
    url: "https://www.bea.gov/itable/",
  },
  {
    name: "Eurostat full database",
    publisher: "European Commission / Eurostat",
    description: "Harmonized statistics spanning population, economy, trade, education, energy, environment, transport, and digital society.",
    region: "Europe",
    domain: "Government",
    license: "EU reuse policy · attribution · check exceptions",
    licenseClass: "Attribution",
    access: "Bulk + SDMX API",
    mess: 3,
    lesson: "Dimensional cubes, code lists, harmonization, country exceptions",
    url: "https://ec.europa.eu/eurostat/data/database",
    featured: true,
  },
  {
    name: "GENESIS-Online",
    publisher: "German Federal Statistical Office",
    description: "Germany’s configurable official-statistics database, covering society, economy, environment, and government.",
    region: "Europe",
    domain: "Population",
    license: "DL-DE-BY 2.0",
    licenseClass: "Attribution",
    access: "REST API + tables",
    mess: 3,
    lesson: "German metadata, hierarchical tables, attribution for transformed data",
    url: "https://www-genesis.destatis.de/datenbank/online",
  },
  {
    name: "INSEE open statistical data",
    publisher: "French National Institute of Statistics",
    description: "Population, business, employment, income, prices, geography, and local statistics for France.",
    region: "Europe",
    domain: "Population",
    license: "Licence Ouverte 2.0",
    licenseClass: "Attribution",
    access: "API + files",
    mess: 3,
    lesson: "Administrative geography, French classifications, changing territorial units",
    url: "https://www.insee.fr/en/accueil",
  },
  {
    name: "CBS StatLine",
    publisher: "Statistics Netherlands",
    description: "Thousands of tables on Dutch population, health, welfare, justice, trade, energy, transport, and regional conditions.",
    region: "Europe",
    domain: "Government",
    license: "CC BY 4.0",
    licenseClass: "Attribution",
    access: "OData API + bulk",
    mess: 2,
    lesson: "OData, table metadata, bilingual dimensions, regional comparison",
    url: "https://opendata.cbs.nl/",
  },
  {
    name: "Statistics Finland open data",
    publisher: "Statistics Finland",
    description: "National, municipal, postal-code, grid, and classification data through a well-documented PX-Web ecosystem.",
    region: "Europe",
    domain: "Government",
    license: "CC BY 4.0",
    licenseClass: "Attribution",
    access: "PX-Web + GIS APIs",
    mess: 2,
    lesson: "JSON-stat, small-area analysis, classifications, source citation",
    url: "https://stat.fi/en/services/statistical-data-services/open-data-and-interfaces",
  },
  {
    name: "Statistics Sweden open database",
    publisher: "Statistics Sweden",
    description: "Official statistics and geodata exposed through statistical-database and geospatial interfaces.",
    region: "Europe",
    domain: "Government",
    license: "CC0 1.0",
    licenseClass: "Public domain",
    access: "PX-Web + GIS APIs",
    mess: 2,
    lesson: "Multilingual metadata, reproducible queries, public-domain norms",
    url: "https://www.scb.se/en/services/open-data-api/",
  },
  {
    name: "StatBank Norway",
    publisher: "Statistics Norway",
    description: "Roughly 7,500 tables across Norwegian people, economy, society, nature, and regions.",
    region: "Europe",
    domain: "Government",
    license: "CC BY 4.0",
    licenseClass: "Attribution",
    access: "PX-Web API",
    mess: 2,
    lesson: "API cell limits, classifications, geographic comparison",
    url: "https://www.ssb.no/en/api",
  },
  {
    name: "Office for National Statistics",
    publisher: "UK Office for National Statistics",
    description: "UK population, labor, prices, business, health, mortality, census, and geographic data.",
    region: "Europe",
    domain: "Population",
    license: "Open Government Licence 3.0 · unless noted",
    licenseClass: "Attribution",
    access: "API + files",
    mess: 3,
    lesson: "Census geography, revisions, disclosure control, mixed file shapes",
    url: "https://www.ons.gov.uk/",
  },
  {
    name: "GLEIF Legal Entity Identifier data",
    publisher: "Global Legal Entity Identifier Foundation",
    description: "Worldwide legal-entity identifiers, names, addresses, registration authorities, relationships, and status history.",
    region: "Global — filter US/EU",
    domain: "Economy",
    license: "CC0 1.0",
    licenseClass: "Public domain",
    access: "API + Golden Copy files",
    mess: 3,
    lesson: "Entity resolution, corporate hierarchies, identifiers, historical names",
    url: "https://www.gleif.org/en/lei-data/gleif-golden-copy/download-the-golden-copy",
    featured: true,
  },
  {
    name: "Federal Election Commission data",
    publisher: "U.S. Federal Election Commission",
    description: "Candidates, committees, filings, receipts, disbursements, donors, and independent expenditures.",
    region: "US",
    domain: "Government",
    license: "U.S. Public Domain",
    licenseClass: "Public domain",
    access: "API + bulk files",
    mess: 4,
    lesson: "Amended filings, duplicate-looking records, entity names, legal reporting rules",
    url: "https://www.fec.gov/data/",
  },
  {
    name: "College Scorecard",
    publisher: "U.S. Department of Education",
    description: "Institution-level costs, admissions, fields of study, completion, debt, earnings, and student characteristics.",
    region: "US",
    domain: "Government",
    license: "U.S. Public Domain",
    licenseClass: "Public domain",
    access: "API + CSV",
    mess: 3,
    lesson: "Outcome definitions, cohort timing, missingness, causal overreach",
    url: "https://collegescorecard.ed.gov/data/",
  },
  {
    name: "OpenCellID",
    publisher: "Unwired Labs community",
    description: "Crowdsourced cell-tower observations with radio type, network identifiers, approximate location, samples, and timestamps.",
    region: "Global — filter US/EU",
    domain: "Mobility",
    license: "CC BY-SA 4.0",
    licenseClass: "Share-alike",
    access: "Bulk + API",
    mess: 4,
    lesson: "Sampling bias, spatial uncertainty, radio standards, share-alike obligations",
    url: "https://opencellid.org/downloads",
    featured: true,
  },
  {
    name: "OpenStreetMap",
    publisher: "OpenStreetMap Foundation + contributors",
    description: "A continuously edited world map of roads, paths, buildings, places, amenities, transit, and human geography.",
    region: "Global — filter US/EU",
    domain: "Mobility",
    license: "ODbL 1.0",
    licenseClass: "Share-alike",
    access: "Planet file + regional extracts + API",
    mess: 4,
    lesson: "Tag ontology, contributor bias, topology, database share-alike",
    url: "https://planet.openstreetmap.org/",
    featured: true,
  },
  {
    name: "Natural Earth",
    publisher: "Natural Earth contributors",
    description: "Clean, small-scale physical and cultural map layers designed for cartography at global and regional scales.",
    region: "Global — filter US/EU",
    domain: "Environment",
    license: "Public Domain",
    licenseClass: "Public domain",
    access: "Shapefile + GeoPackage",
    mess: 1,
    lesson: "Map scale, generalized geometry, projection choices",
    url: "https://www.naturalearthdata.com/downloads/",
  },
  {
    name: "Airline on-time performance",
    publisher: "U.S. Bureau of Transportation Statistics",
    description: "Flight-level arrival, departure, delay-cause, cancellation, diversion, carrier, and airport records dating to 1995.",
    region: "US",
    domain: "Mobility",
    license: "U.S. Public Domain",
    licenseClass: "Public domain",
    access: "Raw files + query tool",
    mess: 4,
    lesson: "Entity codes over time, local timestamps, missing flights, weather joins",
    url: "https://transtats.bts.gov/ONTIME/",
    featured: true,
  },
  {
    name: "Fatality Analysis Reporting System",
    publisher: "U.S. National Highway Traffic Safety Administration",
    description: "Detailed annual census of fatal motor-vehicle crashes with crash, vehicle, person, roadway, and circumstance tables.",
    region: "US",
    domain: "Mobility",
    license: "U.S. Public Domain",
    licenseClass: "Public domain",
    access: "CSV + SAS + DBF",
    mess: 4,
    lesson: "Relational joins, coded fields, schema drift, denominators",
    url: "https://www.nhtsa.gov/research-data/fatality-analysis-reporting-system-fars",
  },
  {
    name: "Police.uk street-level crime",
    publisher: "UK Home Office / police forces",
    description: "Monthly geocoded crime, outcomes, stop-and-search, neighborhood, and police-force data for much of the UK.",
    region: "Europe",
    domain: "Government",
    license: "Open Government Licence 3.0",
    licenseClass: "Attribution",
    access: "CSV + API",
    mess: 3,
    lesson: "Location anonymization, recorded-crime bias, policing differences",
    url: "https://data.police.uk/",
    featured: true,
  },
  {
    name: "Copernicus Sentinel archive",
    publisher: "European Union / ESA",
    description: "Radar, multispectral, ocean, atmosphere, and land-monitoring satellite observations with deep historical coverage.",
    region: "US + Europe",
    domain: "Environment",
    license: "Copernicus free, full and open licence",
    licenseClass: "Attribution",
    access: "APIs + cloud processing + files",
    mess: 4,
    lesson: "Raster scale, cloud cover, atmospheric correction, compute cost",
    url: "https://dataspace.copernicus.eu/",
    featured: true,
  },
  {
    name: "ERA5 climate reanalysis",
    publisher: "ECMWF / Copernicus Climate Change Service",
    description: "Hourly global estimates of atmospheric, land, and ocean-climate variables combining models with observations.",
    region: "US + Europe",
    domain: "Environment",
    license: "CC BY 4.0",
    licenseClass: "Attribution",
    access: "Climate Data Store API",
    mess: 4,
    lesson: "Reanalysis is modeled, gridded time series, huge files, spatial aggregation",
    url: "https://cds.climate.copernicus.eu/datasets/reanalysis-era5-single-levels",
    featured: true,
  },
  {
    name: "NOAA Climate Data Online",
    publisher: "U.S. National Centers for Environmental Information",
    description: "Weather-station observations, climate normals, extremes, radar, ocean, and historical climate products.",
    region: "US + Europe",
    domain: "Environment",
    license: "U.S. Public Domain / CC0 · verify external contributions",
    licenseClass: "Public domain",
    access: "API + files",
    mess: 4,
    lesson: "Station moves, missing intervals, measurement changes, spatial interpolation",
    url: "https://www.ncei.noaa.gov/cdo-web/",
  },
  {
    name: "Landsat Collection 2",
    publisher: "U.S. Geological Survey / NASA",
    description: "Decades of multispectral Earth imagery suitable for land-cover, agriculture, water, fire, and urban-change analysis.",
    region: "US + Europe",
    domain: "Environment",
    license: "U.S. Public Domain",
    licenseClass: "Public domain",
    access: "Cloud + files",
    mess: 4,
    lesson: "Raster QA bands, spectral indices, scene mosaics, temporal comparability",
    url: "https://www.usgs.gov/landsat-missions/landsat-collection-2",
  },
  {
    name: "OpenAQ",
    publisher: "OpenAQ",
    description: "Aggregated ground-level air-quality measurements from government and research providers worldwide.",
    region: "Global — filter US/EU",
    domain: "Environment",
    license: "Per-source machine-readable open licence",
    licenseClass: "Open-filtered",
    access: "API + cloud archive",
    mess: 4,
    lesson: "Unit normalization, station coverage, source-level licensing, sensor quality",
    url: "https://openaq.org/",
  },
  {
    name: "WorldPop gridded population",
    publisher: "University of Southampton",
    description: "High-resolution population estimates by age, sex, and other attributes, useful for converting boundaries into population surfaces.",
    region: "US + Europe",
    domain: "Population",
    license: "CC BY 4.0 · verify product",
    licenseClass: "Attribution",
    access: "GeoTIFF + API",
    mess: 3,
    lesson: "Modeled estimates, raster populations, uncertainty, census-year mismatch",
    url: "https://www.worldpop.org/datacatalog/",
  },
  {
    name: "European Environment Agency Datahub",
    publisher: "European Environment Agency",
    description: "European air, water, emissions, waste, climate, land, biodiversity, and environmental-policy datasets.",
    region: "Europe",
    domain: "Environment",
    license: "CC BY 4.0 · verify item",
    licenseClass: "Attribution",
    access: "Files + spatial services",
    mess: 3,
    lesson: "Reporting obligations, country completeness, geospatial metadata",
    url: "https://www.eea.europa.eu/en/datahub",
  },
  {
    name: "GBIF species occurrences",
    publisher: "Global Biodiversity Information Facility",
    description: "Billions of specimen and observation records with taxonomy, place, date, collection method, and data provenance.",
    region: "Global — filter US/EU",
    domain: "Environment",
    license: "Filter to CC0 or CC BY 4.0",
    licenseClass: "Open-filtered",
    access: "API + DOI downloads",
    mess: 4,
    lesson: "Taxonomic drift, observer bias, sensitive locations, mixed licenses",
    url: "https://www.gbif.org/occurrence/search",
    featured: true,
  },
  {
    name: "EPA Envirofacts",
    publisher: "U.S. Environmental Protection Agency",
    description: "Facility, permit, toxic-release, waste, water, air, chemical, and compliance records across many regulatory systems.",
    region: "US",
    domain: "Environment",
    license: "U.S. Public Domain · verify source exceptions",
    licenseClass: "Public domain",
    access: "REST API + files",
    mess: 4,
    lesson: "Facility identity, regulatory silos, address matching, reporting thresholds",
    url: "https://www.epa.gov/enviro/envirofacts-data-service-api",
  },
  {
    name: "U.S. Energy Information Administration",
    publisher: "U.S. EIA",
    description: "Electricity, petroleum, gas, coal, renewables, consumption, prices, reserves, and emissions time series.",
    region: "US",
    domain: "Economy",
    license: "U.S. Public Domain · cite source",
    licenseClass: "Public domain",
    access: "API + files",
    mess: 3,
    lesson: "Energy units, balancing authorities, revisions, geographic aggregation",
    url: "https://www.eia.gov/opendata/",
  },
  {
    name: "Data.gov",
    publisher: "U.S. General Services Administration",
    description: "The federal metadata catalog linking to hundreds of thousands of datasets across agencies and topics.",
    region: "US",
    domain: "Government",
    license: "Filter to U.S. Public Domain / explicit open licence",
    licenseClass: "Open-filtered",
    access: "Catalog API + source links",
    mess: 4,
    lesson: "Metadata quality, broken links, federal versus non-federal rights",
    url: "https://data.gov/",
  },
  {
    name: "data.europa.eu",
    publisher: "Publications Office of the European Union",
    description: "A cross-border catalog harvesting national, regional, local, and EU open-data portals across Europe.",
    region: "Europe",
    domain: "Government",
    license: "Filter to an Open Definition-conformant licence",
    licenseClass: "Open-filtered",
    access: "CKAN API + source links",
    mess: 4,
    lesson: "Hundreds of licence labels, multilingual metadata, catalog federation",
    url: "https://data.europa.eu/en",
  },
  {
    name: "Wikidata",
    publisher: "Wikimedia Foundation + contributors",
    description: "A collaborative knowledge graph linking people, places, organizations, concepts, identifiers, and source claims.",
    region: "US + Europe",
    domain: "Knowledge",
    license: "CC0 1.0",
    licenseClass: "Public domain",
    access: "SPARQL + API + dumps",
    mess: 4,
    lesson: "Knowledge graphs, provenance, incomplete properties, community ontology",
    url: "https://www.wikidata.org/wiki/Wikidata:Data_access",
    featured: true,
  },
  {
    name: "OpenAlex",
    publisher: "OurResearch",
    description: "An open scholarly graph of works, authors, institutions, sources, topics, funders, and citations.",
    region: "US + Europe",
    domain: "Knowledge",
    license: "CC0 1.0",
    licenseClass: "Public domain",
    access: "API + full snapshot",
    mess: 3,
    lesson: "Author disambiguation, citation graphs, coverage bias, concept drift",
    url: "https://openalex.org/",
  },
  {
    name: "Crossref metadata",
    publisher: "Crossref members",
    description: "DOI-centered scholarly metadata for articles, books, datasets, grants, funders, updates, and relationships.",
    region: "US + Europe",
    domain: "Knowledge",
    license: "Mostly facts / CC0 · abstracts may differ",
    licenseClass: "Open-filtered",
    access: "REST API + annual file",
    mess: 4,
    lesson: "Sparse metadata, publisher variation, DOI matching, rights at field level",
    url: "https://www.crossref.org/documentation/retrieve-metadata/",
  },
  {
    name: "ORCID public data file",
    publisher: "ORCID",
    description: "Public researcher identifiers and self-curated affiliations, works, funding, education, and external identifiers.",
    region: "US + Europe",
    domain: "Knowledge",
    license: "CC0 1.0",
    licenseClass: "Public domain",
    access: "Annual bulk file + API",
    mess: 4,
    lesson: "Self-reported data, identity resolution, privacy settings, temporal affiliations",
    url: "https://info.orcid.org/documentation/integration-guide/working-with-bulk-data/",
  },
  {
    name: "Europeana metadata",
    publisher: "Europeana Foundation + cultural institutions",
    description: "Metadata for European art, archaeology, books, archives, music, fashion, photography, and cultural heritage.",
    region: "Europe",
    domain: "Culture",
    license: "CC0 1.0 metadata · object rights vary",
    licenseClass: "Public domain",
    access: "API + linked open data",
    mess: 4,
    lesson: "Metadata/content rights split, multilingual descriptions, institution bias",
    url: "https://www.europeana.eu/en/rights/usage-guidelines-for-metadata",
    featured: true,
  },
  {
    name: "Smithsonian Open Access",
    publisher: "Smithsonian Institution",
    description: "Millions of collection records, 2D and 3D media, natural-history specimens, research assets, and cultural objects.",
    region: "US",
    domain: "Culture",
    license: "CC0 1.0 items",
    licenseClass: "Public domain",
    access: "API + GitHub + media",
    mess: 3,
    lesson: "Collection metadata, ethical reuse, object/media rights, missing digitization",
    url: "https://www.si.edu/openaccess",
  },
  {
    name: "The Met Collection API",
    publisher: "Metropolitan Museum of Art",
    description: "Collection metadata and hundreds of thousands of open-access artwork images spanning 5,000 years.",
    region: "US",
    domain: "Culture",
    license: "CC0 1.0 open-access data + images",
    licenseClass: "Public domain",
    access: "API",
    mess: 2,
    lesson: "Search APIs, art classifications, provenance, sparse dates",
    url: "https://metmuseum.github.io/",
  },
  {
    name: "National Vulnerability Database",
    publisher: "U.S. National Institute of Standards and Technology",
    description: "CVE vulnerabilities enriched with products, severity scores, weakness classes, references, and configurations.",
    region: "US + Europe",
    domain: "Technology",
    license: "U.S. Public Domain",
    licenseClass: "Public domain",
    access: "API + JSON feeds",
    mess: 4,
    lesson: "Nested JSON, delayed enrichment, version matching, severity changes",
    url: "https://nvd.nist.gov/vuln/data-feeds",
    featured: true,
  },
  {
    name: "Stack Exchange public content",
    publisher: "Stack Exchange community",
    description: "Questions, answers, comments, tags, votes, and revision histories across technical and professional communities.",
    region: "US + Europe",
    domain: "Technology",
    license: "CC BY-SA 2.5 / 3.0 / 4.0 by contribution date",
    licenseClass: "Share-alike",
    access: "API + data dump",
    mess: 4,
    lesson: "Version-specific licensing, text analysis, community bias, temporal reputation",
    url: "https://stackoverflow.com/help/licensing",
  },
];

export const domains = [
  "All",
  "Health",
  "Wearables",
  "Population",
  "Economy",
  "Environment",
  "Mobility",
  "Government",
  "Knowledge",
  "Culture",
  "Technology",
] as const;

export const messLabels = ["", "Ready", "Tidy", "Real-world", "Wild"];
